#! /bin/bash

# fail on first error
set -e
# This script generates a git tag name
# The format for the tag is $WORKSPACE-$COMMIT_HASH_SHORT or $WORKSPACE (see below)
# Where
# WORKSPACE is the workspace that we are generating the tag for. This really equates to the Jira task number
# USE_COMMIT_HASH if set will use the commit hash to generate the tag
# COMMIT_HASH - pass in the commit hash at head of branch not commit hash generated by github pr process
# see https://stackoverflow.com/questions/68061051/get-commit-sha-in-github-actions

EXPORTS_SET=0

if [ -z "$WORKSPACE" ] ; then
    echo WORKSPACE not set
    EXPORTS_SET=1
fi

if [ -z "$USE_COMMIT_HASH" ] ; then
    echo USE_COMMIT_HASH not set
    EXPORTS_SET=1
else
  if [ "$USE_COMMIT_HASH" == "yes" ] && [ -z "$COMMIT_HASH" ]  ; then
    echo Set to use commit hash but no COMMIT_HASH set
    EXPORTS_SET=1
  fi
fi

if [ $EXPORTS_SET = 1 ] ; then
  echo One or more parameters not set
  exit 1
fi

echo "Generate Tag Name Script invoked with the following parameters: "
echo "WORKSPACE: $WORKSPACE"
echo "USE_COMMIT_HASH: $USE_COMMIT_HASH"
echo "COMMIT_HASH: $COMMIT_HASH"

if [ "$USE_COMMIT_HASH" == "yes" ]; then
  TAG_NAME="$WORKSPACE-$COMMIT_HASH"
else
  TAG_NAME="$WORKSPACE"
fi

echo "Generated tag: $TAG_NAME"

export TAG_NAME
