name: "Derive Terraform Version"
description: "Derive max version of terraform"

outputs:
  tf_max_version:
    description: "The max acceptable vers of terraform"
    value: ${{ steps.minMax.outputs.maxVersion }}

runs:
  using: "composite"
  steps:
    - name: Extract Terraform min/max versions
      id: minMax
      uses: clowdhaus/terraform-min-max@main
      with:
        directory: ./infrastructure/remote
