name: "Derive Terraform Version"
description: "Derive max version of terraform"

inputs:
  git_ref:
    description: "The git tag to checkout or current branch if not passed in"
    required: false

outputs:
  tf_max_version:
    description: "The max acceptable vers of terraform"
    value: ${{ steps.minMax.outputs.maxVersion }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{inputs.git_ref}}

    - name: Extract Terraform min/max versions
      id: minMax
      uses: clowdhaus/terraform-min-max@main
      with:
        directory: ./infrastructure/remote
