name: "Derive Terraform Version action"
description: "Derives the maximum version of terraform that the code base supports"

outputs:
  tf_max_version:
    description: "The maximum version of terraform supported by the code base"
    value: ${{ steps.minMax.outputs.maxVersion }}

runs:
  using: "composite"
  steps:
    - name: Extract Terraform min/max versions
      id: minMax
      uses: clowdhaus/terraform-min-max@task/DR-5965_Add_scripts_version2
      with:
        directory: ./infrastructure/remote
