name: "Derive branch name action"
description: "Derives the name of the branch for subsequent actions to run against"

outputs:
    branchname:
        description: "The derived branch name"
        value: ${{ steps.derive-branch.outputs.branchname }}

runs:
  using: "composite"
  steps:
    - name: "Derive branchname"
      id: "derive-branch"
      shell: bash
      run: |
        echo "branchname $(git rev-parse --abbrev-ref HEAD)"
        echo "branchname=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
        fi
