name: "Collect artefact address action"
description: "Collects the artefact sub directory and commit has for pipeline being executed"

inputs:
  artefact-tag:
      description: "The git tag to derive artefact location from"
      required: true
outputs:
  commit_hash:
    description: "Commit hash for head of branch being processed"
    value: ${{ steps.artefact-address.outputs.commit_hash }}
  artefact_sub_dir:
    description: "The unique commit hash for artefacts for flows triggered by a pull request "
    value: ${{ steps.artefact-address.outputs.artefact_sub_dir }}
runs:
  using: "composite"
  steps:
    - name: "Get artefact address "
      id: "artefact-address"
      shell: bash
      run : |
          export ARTEFACT_TAG="${{ inputs.artefact-tag }}"
          echo "ARTEFACT_TAG=$ARTEFACT_TAG" >> $GITHUB_OUTPUT

          artefact_sub_dir=$(echo $ARTEFACT_TAG | cut -d'-' -f1-2)
          commit_hash=$(echo $ARTEFACT_TAG | cut -d'-' -f3)

          echo "Artefact Sub Directory: $artefact_sub_dir"
          echo "Commit Hash: $commit_hash"

          echo "artefact_sub_dir=$artefact_sub_dir" >> $GITHUB_OUTPUT
          echo "commit_hash=$commit_hash" >> $GITHUB_OUTPUT
