name: "Collect artefact address action"
description: "Collects the artefact sub directory and commit has for pipeline being executed"

inputs:
  tag:
      description: "The git tag to derive artefact location from"
      required: true
outputs:
  commit_hash:
    description: "Commit hash for derived from the Tag to identify artefact address"
    value: ${{ steps.artefact-address.outputs.commit_hash }}
  artefact_sub_dir:
    description: "The sub directory derived from the tag to identify the artefact address  "
    value: ${{ steps.artefact-address.outputs.artefact_sub_dir }}
runs:
  using: "composite"
  steps:
    - name: "Get artefact address "
      id: "artefact-address"
      shell: bash
      run : |
          export TAG="${{ inputs.tag }}"

          artefact_sub_dir=$(echo "$TAG" | cut -d'-' -f1-2)
          commit_hash=$(echo "$TAG" | cut -d'-' -f3)

          echo "Artefact Sub Directory: $artefact_sub_dir"
          echo "Commit Hash: $commit_hash"

          echo "artefact_sub_dir=$artefact_sub_dir" >> $GITHUB_OUTPUT
          echo "commit_hash=$commit_hash" >> $GITHUB_OUTPUT
