name: "Cleardown terraform state action"
description: "Delete the terraform state"
inputs:
  workspace:
        description: "The name of the workspace to action the infrastructure into."
        required: true
  environment:
        description: "The name of the environment to action the infrastructure into."
        required: true
  stacks:
        description: "A comma separated list of stacks to clear."
        required: true

runs:
  using: composite
  steps:
    - name: Delete terraform state
      id: delete_tf_state
      shell: bash
      run: |
        export TERRAFORM_WORKSPACE_NAME=${{inputs.workspace}}
        export ENVIRONMENT=${{inputs.environment}}
        export STACKS=${{inputs.stacks}}
        ./uec-dos-management/scripts/workflow/cleardown-terraform-state.sh
