name: "Install npm dependencies action"
description: "Installs npm dependencies"

inputs:
  code_directory:
    description: 'Directory that holds package json '
    required: false
    default: 'src/frontend'
runs:
  using: "composite"
  steps:
    - name: Install node dependencies
      id: install_node_dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.code_directory }}
