name: "Check formatting of javascript code action"
description: "Checks correct formatting of javascript and typescript code in the repository"

inputs:
  code_directory:
    description: 'Directory that holds package json '
    required: true
runs:
  using: "composite"
  steps:
    - name: Checking format of javascript and typescript code
      id: format_javascript
      shell: bash
      run: |
        export FRONT_END_DIR=${{ inputs.code_directory }}
        ./scripts/githooks/front-end-npm-lint-pre-commit.sh

