name: "Deploy react app to s3 bucket"
description: "Deploys react code to hosting s3 bucket"

inputs:
  code_directory:
    description: 'Directory that holds package json for react code '
    required: true
  spa_bucket_name:
    description: 'S3 bucket to host application'
    required: true
  environment:
    description: "The name of the environment to deploy into"
    required: true
  workspace:
    description: "The name of the workspace to deploy the application into"
    required: true
  commit_hash:
    description: "Git commit hash - to locate artefacts"
    required: true
  domain:
    description: "Name of repository - to locate artefacts"
    required: true
runs:
  using: "composite"
  steps:
    - name: Deploys react app to host s3 bucket
      id: npm_deploy_app
      shell: bash
      run: |
        export FRONT_END_DIR=${{ inputs.code_directory }}
        export SPA_BUCKET_NAME=${{ inputs.spa_bucket_name }}
        export COMMIT_HASH=${{ inputs.commit_hash }}
        export WORKSPACE=${{ inputs.workspace }}
        export DOMAIN=${{ inputs.domain }}
        export ENVIRONMENT=${{ inputs.environment }}
        /bin/bash ./uec-dos-management/scripts/workflow/react-deploy.sh
