name: "Configure Credentials action"
description: "Wrapper for the configure AWS credentials action"

inputs:
  secret_account_id:
    description: "The account to retrieve credentials from"
    required: true
  aws_region:
    description: "The AWS region where the account resides"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: arn:aws:iam::${{ inputs.secret_account_id }}:role/${{ github.event.repository.name }}-github-runner
        role-session-name: github-pipeline-session
        aws-region: ${{ inputs.aws_region }}
