name: "Configure Credentials action"
description: "Wrapper for the configure AWS credentials action"

inputs:
  aws_account_id:
    description: "The account to retrieve credentials from"
    required: true
  aws_region:
    description: "The AWS region where the account resides"
    required: true
  int_domain:
    description: "The name of the domain to deploy from. If not supplied, we will deploy from the domain that has invoked the workflow"
    required: false
    default: ""
    type: string

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.int_domain != '' && inputs.int_domain || github.event.repository.name }}-github-runner
        role-session-name: github-pipeline-session
        aws-region: ${{ inputs.aws_region }}
