name: "Derive commit hash action"
description: "Derives commit hash - used to locate pre-built artefacts "
inputs:
  commit_hash:
    description: "The suggested commit hash"
    required: true
outputs:
    commit_hash:
        description: "The derived commit hash"
        value: ${{ steps.derive-commit-hash.outputs.commit_hash }}

runs:
  using: "composite"
  steps:
    - name: "Derive commit hash"
      id: "derive-commit-hash"
      shell: bash
      run: |
        if [ ${{ inputs.commit_hash}} == 'latest' ]; then
          LATEST_HASH=$(git rev-parse --short main)
          export COMMIT_HASH=$(git rev-parse --short main)
          # echo "commit_hash=${LATEST_HASH}" >> $GITHUB_OUTPUT
        else
          export COMMIT_HASH="${{ inputs.commit_hash }}"
          # echo "commit_hash=${{ inputs.commit_hash }}" >> $GITHUB_OUTPUT
        fi
        echo "COMMIT_HASH = ${COMMIT_HASH}"
        echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT
