name: "Derive git hash for branch action"
description: "Derives the short version of the commit hash for branch"
inputs:
    sha:
        description: "The sha from which to derive short version of commit hash"
        required: true
outputs:
    commit_hash:
        description: "The derived short version of the git commit hash "
        value: ${{ steps.derive-short-hash.outputs.commit_hash }}

runs:
  using: "composite"
  steps:
    - name: "Derive git hash"
      id: "derive-short-hash"
      shell: bash
      run: |
        echo not used
        # export SHA=${{ inputs.sha }}
        # /bin/bash ./uec-dos-management/scripts/workflow/derive-hash-from-sha.sh
        # echo "Setting commit hash: ${COMMIT_HASH}"
        # echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT

