name: "Runs npm build of javascript code action"
description: "Runs npm build on react code in the repository"

inputs:
  code_directory:
    description: 'Directory that holds package json for react code '
    required: true
runs:
  using: "composite"
  steps:
    - name: Build react app from javascript and typescript code
      id: npm_build
      shell: bash
      run: |
        export FRONT_END_DIR=${{ inputs.code_directory }}
        /bin/bash ./uec-dos-management/scripts/workflow/npm-build.sh
