name: "Build service action"
description: "Builds a service."

inputs:
    service:
        description: "The name of the service to build"
        required: true


runs:
  using: "composite"

  steps:
      - name: Build Service
        shell: bash
        run: |
          export SERVICE=${{ inputs.service }}
          /bin/bash ./uec-dos-management/scripts/workflow/action-infra-stack.sh
