name: "Upload artefact action"
description: "Wrapper for the upload-artefact action"

inputs:
    retention-days:
        description: "The name number of days to retain upload artefact"
        required: true
    name:
        description: "The name of artefact to be uploaded."
        required: true
    path:
        description: "Path to the artefact to be uploaded"
        required: true

runs:
  using: "composite"

  steps:
    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention-days }}

