name: "Check formatting of general files action"
description: "Checks correct formatting of files in the repository"

runs:
  using: "composite"
  steps:
    - name: Check general formatting
      id: format_general
      shell: bash
      run: |
        export BRANCH_NAME=origin/${{ github.event.repository.default_branch }}
        ./scripts/githooks/editorconfig-pre-commit.sh

