name: "Check formatting of markdown files action"
description: "Checks correct formatting of markdown files in the repository"

runs:
  using: "composite"
  steps:
    - name: Checking format of markdown files
      id: format_markdown
      shell: bash
      run: |
        ./scripts/githooks/check-markdown-format.sh

