name: "Deploy service action"
description: "Deploys a service into a Lambda."

inputs:
    service:
        description: "The name of the service to deploy"
        required: true
    directory:
        description: "The name of the directory to build in"
        required: true
    workspace:
        description: "The name of the workspace to deploy the service into."
        required: true
    commit_hash:
        description: "The short version of the git commit hash"
        required: true
    reponame:
        description: "Name of domain repo to identify artefact bucket"
        required: true
    environment:
        description: "The environment being updated"
        required: true
    tag:
      description: "The version of the service to deploy"
      required: false

runs:
  using: "composite"

  steps:
      - name: Deploy Service
        shell: bash
        run: |
          export SERVICE=${{ inputs.service }}
          export DIRECTORY=${{ inputs.directory }}
          export TAG=${{ inputs.tag }}
          export WORKSPACE=${{ inputs.workspace }}
          export COMMIT_HASH=${{ inputs.commit_hash }}
          export REPO_NAME=${{ inputs.repo_name }}
          export ENVIRONMENT=${{ inputs.environment }}
          /bin/bash ./uec-dos-management/scripts/workflow/deploy-service.sh
