name: "Runs npm linting of javascript code action"
description: "Runs npm linting on react code in the repository"

inputs:
  code_directory:
    description: 'Directory that holds package json for react code '
    required: true
runs:
  using: "composite"
  steps:
    - name: Run lint function over javascript and typescript code
      id: npm_lint_javascript
      shell: bash
      run: |
        export FRONT_END_DIR=${{ inputs.code_directory }}
        /bin/bash ./uec-dos-management/scripts/workflow/npm-lint.sh

