name: "Install python action"
description: "Installs python"

inputs:
  python_version:
    description: 'Version of python'
    default: "3.9"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install python
      id: install_python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

