name: "Code Line Count"
description: "Counts lines of code in the repository"

runs:
  using: "composite"
  steps:
    - name: "Get code line count"
      id: "code-line-count"
      shell: bash
      run: |
        export FORMAT=default
        ./scripts/cloc-repository.sh
