name: "Count line code action"
description: "Counts lines of code in the repository"

runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: "Get code line count"
      id: "code-line-count"
      shell: bash
      run: |
        export FORMAT=default
        ./scripts/cloc-repository.sh
