name: "Derive bucket name for domain artefact"
description: "Derives the name of the bucket used to store artefacts for subsequent actions to run against"

inputs:
    domain:
        description: "The name of the domain to deploy from. If not supplied, we will deploy from the domain that has invoked the workflow"
        required: false
        default: ""
outputs:
    artefact_bucket_name:
        description: "The derived name of s3 bucket to hold artefacts"
        value: ${{ steps.derive-artefact-bucket.outputs.artefact_bucket_name }}

runs:
  using: "composite"
  steps:
    - name: "Derive name of artefact bucket"
      id: "derive-artefact-bucket"
      shell: bash
      run: |
        echo not used
        artefact_bucket_name="nhse-mgmt-${{ inputs.domain }}-artefacts"
        echo "artefact_bucket_name=$artefact_bucket_name" >> $GITHUB_OUTPUT
