name: "Derive Cloudnfront distribution id action"
description: "Derives the id of the cloudfront distribution built"

inputs:
    environment:
        description: "The name of the environment to action the infrastructure"
        required: true
    workspace:
        description: "The name of the workspace to action the infrastructure into."
        required: true
    domain:
        description: "The name of the domain to deploy from. If not supplied, we will deploy from the domain that has invoked the workflow"
        required: false
        default: ""
outputs:
    cloudfront_dist_id:
        description: "The id of the current cloudfront distribution"
        value: "${{ steps.get_cloudfront_dist_id.outputs.distribution_id }}"

runs:
  using: "composite"
  steps:
    - name: Get CloudFront Distribution ID
      id: get_cloudfront_dist_id
      shell: bash
      run: |
        export ENVIRONMENT=${{ inputs.environment }}
        export WORKSPACE=${{ inputs.workspace }}
        export DOMAIN=${{ inputs.domain }}
        distribution_id=$(/bin/bash ./uec-dos-management/scripts/workflow/get-front-end-cloudfront-distribution.sh)
        echo "distribution_id=${distribution_id}"
        echo "distribution_id=${distribution_id}" >> $GITHUB_OUTPUT
