name: "Integration tests action"
description: "Run integration tests"

inputs:
  workspace:
    description: "The name of the workspace to deploy the application into"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run integration test script
      id: run-integration-test-script
      shell: bash
      run: |
        export WORKSPACE=${{ inputs.workspace }}
        /bin/bash ./uec-dos-management/scripts/workflow/integration-tests.sh
