name: "Derive bucket name for SPA action"
description: "Derives the name of the bucket used to store the SPA for subsequent actions to run against"

inputs:
    environment:
        description: "The name of the environment to action the infrastructure"
        required: true
    workspace:
        description: "The name of the workspace to action the infrastructure into."
        required: true
    domain:
        description: "The name of the domain to deploy from. If not supplied, we will deploy from the domain that has invoked the workflow"
        required: false
        default: ""
outputs:
    spa_bucket_name:
        description: "The derived name of s3 bucket to hold SPA"
        value: ${{ steps.derive-spa-bucket.outputs.spa_bucket_name }}

runs:
  using: "composite"
  steps:
    - name: "Derive name of SPA bucket"
      id: "derive-spa-bucket"
      shell: bash
      run: |
        SPA_BUCKET_NAME="nhse-${{ inputs.domain }}-${{ inputs.environment }}-front-end"
        if [[ "${{ inputs.workspace }}" != "default" ]]; then
          SPA_BUCKET_NAME="${SPA_BUCKET_NAME}-${{ inputs.workspace }}"
        fi
        echo "spa_bucket_name=$SPA_BUCKET_NAME" >> $GITHUB_OUTPUT
