name: "Derive bucket name for SPA action"
description: "Derives the name of the bucket used to store the SPA for subsequent actions to run against"

inputs:
    environment:
        description: "The name of the environment to action the infrastructure"
        required: true
    workspace:
        description: "The name of the workspace to action the infrastructure into."
        required: true
    repo_name:
        description: "The name of the repository"
        required: true
outputs:
    spa_bucket_name:
        description: "The derived name of s3 bucket to hold SPA"
        value: ${{ steps.derive-spa-bucket.outputs.spa_bucket_name }}

runs:
  using: "composite"
  steps:
    - name: "Derive name of SPA bucket"
      id: "derive-spa-bucket"
      shell: bash
      run: |
        SPA_BUCKET_NAME="nhse-${{ input.repo_name }}-${{ input.environment }}-front-end"
        if [[ "${{ input.workspace }}" != "default" ]]; then
          SPA_BUCKET_NAME="${SPA_BUCKET_NAME}-${{ input.workspace }}"
        fi

        echo "spa_bucket_name=${SPA_BUCKET_NAME}" >> $GITHUB_OUTPUT
