name: "Upload react app artefact"
description: "Upload the built react app artefacts to s3 bucket"

inputs:
    workspace:
        description: "The name of the workspace to build into."
        required: true
    commit_hash:
        description: "The unique commit hash"
        required: true
        type: string
    artefact_bucket_name:
        description: "The name of the artefact bucket"
        required: true
        type: string
    code_directory:
        description: 'Directory that holds package json for react code '
        required: true

runs:
  using: "composite"

  steps:
      - name: Build react app
        shell: bash
        run: |
          export FRONT_END_DIR=${{ inputs.code_directory }}
          export WORKSPACE=${{ inputs.workspace }}
          export COMMIT_HASH=${{ inputs.commit_hash }}
          export ARTEFACT_BUCKET_NAME=${{ inputs.artefact_bucket_name }}
          /bin/bash ./uec-dos-management/scripts/workflow/push-react-artefact.sh
