name: "Check formatting of terraform code"
description: "Checks correct formatting of terraform code in the repository"

# inputs:
  # tf_version:
  #   description: 'Version of terraform used to validate stack'
  #   required: true
  # stack:
  #   description: 'Terraform stack to validate'
  #   required: true
  # account_type:
  #   description: "Purpose of aws account eg dev, test"
  #   required: true
runs:
  using: "composite"
  steps:
    - name: Check formatting of tf code
      id: format_terraform
      shell: bash
      run: |
        export CHECK_ONLY=true
        ./scripts/githooks/check-terraform-format.sh

