name: "Clear cloudfront cache action"
description: "Clears cache for deployed react app"

inputs:
  code_directory:
    description: 'Directory that holds package json for react code '
    required: true
  distribution_id:
    description: 'Id of cloudfront distribution from which to clear cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: Deploys react app to host s3 bucket
      id: npm_deploy_app
      shell: bash
      run: |
        export FRONT_END_DIR=${{ inputs.code_directory }}
        export DISTRIBUTION_ID=${{ inputs.distribution_id }}
        /bin/bash ./uec-dos-management/scripts/workflow/invalidate-cloudfront-cache.sh
