name: "Checkout Repository action"
description: "Wrapper for the checkout action to give options of checking out from other repositories and from a given tag in the history of the repository"

inputs:
  repository:
    description: "The code repository to checkout"
    required: false
    default: ${{ github.event.repository.name }}
  tag:
    description: "The tag in the repository history to checkout"
    required: false
    default: ''
  management-tag:
    description: "Version of the uec-dos-management repo to checkout"
    required: false
    default: latest
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags; default is 1"
    required: false
    default: ''
  sparse-checkout:
    description: "Specific paths of the code repository to check out"
    required: false
    default: ''
  path:
    description: "Relative location defining where to checkout the code into"
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: "NHSDigital/${{ inputs.repository }}"
        ref: ${{ inputs.tag }}
        fetch-depth: ${{ inputs.fetch-depth }}
        sparse-checkout: ${{ inputs.sparse-checkout }}
        path: ${{ inputs.path }}
    - name: Checkout Management Repository
      uses: actions/checkout@v4
      with:
        repository:  "NHSDigital/uec-dos-management"
        ref: ${{ inputs.management-tag }}
        sparse-checkout: |
          scripts/workflow
        path: 'uec-dos-management'
