name: "Checkout Management Repository action"
description: "Wrapper for the checkout action of the uec-dos-management repository from a given tag in the history of the repository"

runs:
  using: "composite"
  steps:
    - name: Checkout Mangement Repository
      uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@task/DR-5967_Sparse_checkout_repo
      with:
        repository: uec-dos-management
        tag: task/DR-5967_Sparse_checkout_repo
        sparse-checkout: |
          scripts
        path: 'uec-dos-management'
