name: "domain tests action"
description: "Run domain tests"

inputs:
    environment:
      description: "The name of the environment to action the infrastructure"
      required: true
    workspace:
      description: "The name of the workspace to action the infrastructure into."
      required: true
    aws_region:
      description: "AWS region"
      required: true


runs:
  using: "composite"
  steps:
    - name: Run domain test script
      id: run-domain-test-script
      shell: bash
      run: |
        export AWS_REGION=${{ inputs.aws_region }}
        export WORKSPACE=${{ inputs.workspace }}
        export ENVIRONMENT=${{ inputs.environment }}
        pwd
        /bin/bash ./uec-dos-management/scripts/workflow/domain-tests.sh
