name: "Runs unit testing of javascript code action"
description: "Runs unit tests of react code in the repository"

inputs:
  code_directory:
    description: 'Directory that holds package json for react code '
    required: true
runs:
  using: "composite"
  steps:
    - name: Run unit tests of javascript and typescript code
      id: npm_unit_test
      shell: bash
      run: |
        export FRONT_END_DIR=${{ inputs.code_directory }}
        /bin/bash ./uec-dos-management/scripts/workflow/npm-unit-tests.sh

