name: Build and Deploy Application workflow

on:
  workflow_call:
    inputs:
      environment:
            description: "The name of the environment to deploy into"
            required: true
            type: string
      workspace:
            description: "The name of the workspace to deploy the application into"
            required: true
            type: string
      services:
            description: "A list of the services to build and deploy"
            required: false
            default: ""
            type: string
      tag:
            description: "The tag to build and deploy from"
            required: false
            default: ""
            type: string
      workflow_timeout:
        description: "Timeout duration in minutes"
        required: false
        default: 5
        type: number

jobs:
  build-application:
    name: "Build Application"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    timeout-minutes: ${{ inputs.workflow_timeout }}
    strategy:
      matrix:
        service: ${{ fromJSON(inputs.services) }}
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.18
        with:
          tag: ${{ inputs.tag }}

      - name: Configure AWS Credentials
        uses: NHSDigital/uec-dos-management/.github/actions/configure-credentials@v0.18
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}

      - name: "Build service"
        uses: NHSDigital/uec-dos-management/.github/actions/build-service@v0.18
        with:
          service: ${{ matrix.service }}
          directory: ${{ inputs.directory }}

      - name: "Deploy service"
        uses: NHSDigital/uec-dos-management/.github/actions/deploy-service@v0.18
        with:
          service: ${{ matrix.service }}
          directory: ${{ inputs.directory }}
          workspace: ${{ inputs.workspace }}
