name: Build Full Application workflow

on:
  workflow_call:
    inputs:
      target_repo:
        description: "The name of the repo"
        required: true
        type: string
      target_repo_branch:
        description: "The name of the target repo branch"
        required: true
        type: string

jobs:
  build-full-application:
    name: "Build Full Application"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@latest
        with:
          tag: ${{ inputs.tag }}

      - name: Configure AWS Credentials
        uses: NHSDigital/uec-dos-management/.github/actions/configure-credentials@latest
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
