name: Build Full Application workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment to build into"
        required: true
        type: string
      workspace:
        description: "The name of the workspace to build the application into"
        required: true
        type: string
      services:
        description: "A list of the services to build"
        required: false
        default: ""
        type: string
      tag:
        description: "The tag to build from"
        required: false
        default: ""
        type: string
      workflow_timeout:
        description: "Timeout duration in minutes"
        required: false
        default: 5
        type: number
      # target_repo:
      #   description: "The name of the repo"
      #   required: true
      #   type: string
      # target_repo_commit_hash:
      #   description: "The name of the target repo branch"
      #   required: true
      #   type: string

jobs:
  deploy-infrastructure-apply:
    name: "Apply Deploy Infrastructure"
    strategy:
      matrix:
        domain: "['uec-service-management','uec-cm','uec-account-mngt','uec-dos-service-search','uec-dos-user-management','uec-dos-user-interfaces']"
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: int
      workspace: ${{ inputs.workspace }}
      domain: ${{ matrix.domain }}
      stacks: "['application']"
      action: plan
    secrets: inherit

  deploy-lambda-code:
    name: "Deploy Application "
    strategy:
      matrix:
        domain: "['uec-service-management','uec-cm','uec-account-mngt','uec-dos-service-search','uec-dos-user-management','uec-dos-user-interfaces']"
    uses: ./.github/workflows/deploy-lambda-code.yaml
    with:
      environment: int
      workspace: ${{ inputs.workspace }}
      services: "['healthcare-services-data-manager']"
      directory: 'application'
      commit_hash: ${{ needs.metadata.outputs.commit_hash }}
      artefact_bucket_name: ${{ needs.metadata.outputs.artefact_bucket_name }}
    secrets: inherit


  deploy-react-app:
    name: "Deploy react application "
    strategy:
      matrix:
        domain: "['uec-service-management','uec-cm','uec-account-mngt','uec-dos-service-search','uec-dos-user-management','uec-dos-user-interfaces']"
    uses: ./.github/workflows/deploy-react-app.yaml
    with:
      environment: int
      workspace: ${{ inputs.workspace }}
      domain: ${{ matrix.domain }}
      stacks: "['application']"
      action: plan
    secrets: inherit
