name: Build And Deploy React App

on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment to deploy into"
        required: true
        type: string
      workspace:
        description: "The name of the workspace to deploy the application into"
        required: true
        type: string
      domain:
        description: "The name of the code repository"
        required: true
        type: string
      code_directory:
        description: "The root directory for react code"
        required: false
        type: string
        default: "src/frontend"
      tag:
        description: "The tag to build and deploy from"
        required: false
        default: ""
        type: string
      workflow_timeout:
        description: "Timeout duration in minutes"
        required: false
        default: 5
        type: number

jobs:

  build-and-deploy-react-app:
    name: "Prepare, build and deploy react application"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    timeout-minutes: ${{ inputs.workflow_timeout }}
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.14
        with:
          tag: ${{ inputs.tag }}
          repository: ${{ inputs.domain }}

      - name: Configure AWS Credentials
        uses: NHSDigital/uec-dos-management/.github/actions/configure-credentials@v0.14
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}

      - name: Derive spa bucket
        id: derive_spa_bucket
        uses: NHSDigital/uec-dos-management/.github/actions/derive-frontend-bucket@v0.14
        with:
          environment: ${{ inputs.environment }}
          workspace: ${{ inputs.workspace }}
          domain: ${{ inputs.domain }}

      - name: Derive cloudfront dist id
        id: derive_cloudfront_dist_id
        uses: NHSDigital/uec-dos-management/.github/actions/derive-cloudfront-dist-id@v0.14
        with:
          environment: ${{ inputs.environment }}
          workspace: ${{ inputs.workspace }}
          domain: ${{ inputs.domain }}

      - name: Set up Node.js
        uses: NHSDigital/uec-dos-management/.github/actions/install-node@v0.14

      - name: Install dependencies
        uses: NHSDigital/uec-dos-management/.github/actions/install-npm-dependencies@v0.14
        with:
          code_directory: ${{ inputs.code_directory }}

      - name: Run Linter
        uses: NHSDigital/uec-dos-management/.github/actions/react-npm-lint@v0.14
        with:
          code_directory: ${{ inputs.code_directory }}

      - name: Run Unit Tests
        uses: NHSDigital/uec-dos-management/.github/actions/react-npm-unit-tests@v0.14
        with:
          code_directory: ${{ inputs.code_directory }}

      - name: Build React application
        uses: NHSDigital/uec-dos-management/.github/actions/react-npm-build@v0.14
        with:
          code_directory: ${{ inputs.code_directory }}

      - name: Deploy react application
        uses: NHSDigital/uec-dos-management/.github/actions/react-app-deploy@v0.14
        with:
          code_directory: ${{ inputs.code_directory }}
          spa_bucket_name: ${{ steps.derive_spa_bucket.outputs.spa_bucket_name }}

      - name: Invalidate CloudFront Cache
        uses: NHSDigital/uec-dos-management/.github/actions/react_clear_cloudfront_cache@v0.14
        with:
          code_directory: ${{ inputs.code_directory }}
          distribution_id: ${{ steps.derive_cloudfront_dist_id.outputs.cloudfront_dist_id }}
