name: Derive artefact address workflow

on:
  workflow_call:
    inputs:
      artefact-tag:
        description: "The git tag to derive artefact location from"
        required: true
        type: string
      workflow_timeout:
        description: "Timeout duration in minutes"
        required: false
        default: 5
        type: number
    outputs:
      commit_hash:
        description: "The unique commit hash"
        value: ${{ jobs.derive-artefact-address.outputs.commit_hash }}
      artefact_sub_dir:
        description: "The unique workspaced sub directory where artefacts are held"
        value: ${{ jobs.derive-artefact-address.outputs.artefact_sub_dir }}

jobs:

  derive-artefact-address:
    name: "Get Artefact address"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      commit_hash: ${{ steps.get-artefact-address.outputs.commit_hash }}
      artefact_sub_dir: ${{ steps.get-artefact-address.outputs.artefact_sub_dir }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.39
        with:
          tag: ${{ inputs.tag }}
      - name: "Get arteafact address"
        id: get-artefact-address
        uses: NHSDigital/uec-dos-management/.github/actions/derive-artefact-address@v0.39
