name: Derive artefact address workflow

on:
  workflow_call:
    inputs:
      tag:
        description: "The git tag to derive artefact location from"
        required: true
        type: string
    outputs:
      commit_hash:
        description: "The unique commit hash"
        value: ${{ jobs.derive-artefact-address.outputs.commit_hash }}
      artefact_sub_dir:
        description: "The unique workspaced sub directory where artefacts are held"
        value: ${{ jobs.derive-artefact-address.outputs.artefact_sub_dir }}

jobs:

  derive-artefact-address:
    name: "Get Artefact address"
    runs-on: ubuntu-latest

    outputs:
      commit_hash: ${{ steps.get-artefact-address.outputs.commit_hash }}
      artefact_sub_dir: ${{ steps.get-artefact-address.outputs.artefact_sub_dir }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@latest
        with:
          tag: ${{ inputs.tag }}
      - name: "Get arteafact address"
        id: get-artefact-address
        with:
          tag: ${{ inputs.tag }}
        uses: NHSDigital/uec-dos-management/.github/actions/derive-artefact-address@latest
