name: Metadata workflow

on:
  workflow_call:
    inputs:
      tag:
        description: "The git tag to checkout, this defaults to the head of the triggering branch"
        required: false
        type: string
      workflow_timeout:
        description: "Timeout duration in minutes"
        required: false
        default: 5
        type: number
    outputs:
      reponame:
        description: "The name of the code repo"
        value: "${{ jobs.echo-metadata.outputs.reponame }}"
      workspace:
        description: "The name of the workspace that we interacting with"
        value: "${{ jobs.derive-workspace.outputs.workspace }}"
      artefact_bucket_name:
        description: "The s3 bucket for domain artefacts"
        value: ${{ jobs.echo-metadata.outputs.artefact_bucket_name }}
      commit_hash:
        description: "The unique commit hash"
        value: ${{ jobs.echo-metadata.outputs.commit_hash }}
      artefact_commit_hash:
        description: "The unique commit hash for artefacts for flows triggered by a pull request "
        value: ${{ jobs.echo-metadata.outputs.artefact_commit_hash }}

jobs:
  code-line-count:
    name: "Code Line Count"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@latest
        with:
          tag: ${{ inputs.tag }}
      - name: "Code line count"
        uses: NHSDigital/uec-dos-management/.github/actions/code-line-count@latest

  echo-metadata:
    name: "Get Metadata"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      reponame: ${{ steps.get_metadata.outputs.reponame }}
      commit_hash: ${{ steps.get_metadata.outputs.commit_hash }}
      artefact_commit_hash: ${{ steps.get_metadata.outputs.artefact_commit_hash }}
      artefact_bucket_name: ${{ steps.get_metadata.outputs.artefact_bucket_name }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@latest
        with:
          tag: ${{ inputs.tag }}
      - name: "Get metadata"
        id: get_metadata
        uses: NHSDigital/uec-dos-management/.github/actions/metadata@latest

  derive-workspace:
    name: "Derive Workspace"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      workspace: ${{ steps.derive_workspace.outputs.workspace }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@latest
        with:
          tag: ${{ inputs.tag }}
      - name: "Derive workspace"
        id: derive_workspace
        uses: NHSDigital/uec-dos-management/.github/actions/derive-workspace@latest
