name: Metadata workflow

on:
  workflow_call:
    inputs:
        tag:
          description: "The git tag to checkout, this defaults to the head of the triggering branch"
          required: false
          type: string
    outputs:
      reponame:
        description: "The name of the code repo"
        value: "${{ jobs.echo-metadata.outputs.reponame }}"
      tf_max_version:
        description: "The max version of terraform that the code supports"
        value: "${{ jobs.derive-tf-version.outputs.tf_max_version }}"
      derive-workspace:
        description: "The name of the workspace that we interacting with"
        value: "${{ jobs.derive-workspace.outputs.workspace }}"

jobs:
  code-line-count:
    name: "Code Line Count"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@main
        with:
          tag: ${{ inputs.tag }}
      - name: "Code line count"
        uses: NHSDigital/uec-dos-management/.github/actions/code-line-count@main

  derive-tf-version:
    name: "Derive TF Version"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      tf_max_version: ${{ steps.derive_tf_version.outputs.tf_max_version }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@main
        with:
          tag: ${{ inputs.tag }}
      - name: "Derive TF Version"
        id: derive_tf_version
        uses: NHSDigital/uec-dos-management/.github/actions/derive-tf-version@main

  echo-metadata:
    name: "Get Metadata"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    outputs:
      reponame: ${{ steps.get_metadata.outputs.reponame }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@main
        with:
          tag: ${{ inputs.tag }}
      - name: "Get metadata"
        id: get_metadata
        uses: NHSDigital/uec-dos-management/.github/actions/metadata@main

  derive-workspace:
    name: "Derive Workspace"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    outputs:
      workspace: ${{ steps.derive_workspace.outputs.workspace }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
      - name: "Derive workspace"
        id: derive_workspace
        uses: NHSDigital/uec-dos-management/.github/actions/derive-workspace@task/DR-596_Deploy_service_workflow


