name: Metadata workflow

on:
  workflow_call:
    inputs:
      tag:
        description: "The git tag to checkout, this defaults to the head of the triggering branch"
        required: false
        type: string
      workflow_timeout:
        description: "Timeout duration in minutes"
        required: false
        default: 5
        type: number
    outputs:
      reponame:
        description: "The name of the code repo"
        value: "${{ jobs.echo-metadata.outputs.reponame }}"
      workspace:
        description: "The name of the workspace that we interacting with"
        value: "${{ jobs.derive-workspace.outputs.workspace }}"
      commit_hash:
        description: "The unique commit hash"
        value: ${{ jobs.get-commit-hash.outputs.commit_hash }}
      artefact_bucket_name:
        description: "The name of the repo for domain artefacts"
        value: ${{ jobs.derive-artefact-bucket.outputs.artefact_bucket_name }}

jobs:
  code-line-count:
    name: "Code Line Count"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.20
        with:
          tag: ${{ inputs.tag }}
      - name: "Code line count"
        uses: NHSDigital/uec-dos-management/.github/actions/code-line-count@v0.20

  echo-metadata:
    name: "Get Metadata"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      reponame: ${{ steps.get_metadata.outputs.reponame }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.20
        with:
          tag: ${{ inputs.tag }}
      - name: "Get metadata"
        id: get_metadata
        uses: NHSDigital/uec-dos-management/.github/actions/metadata@v0.20

  derive-workspace:
    name: "Derive Workspace"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      workspace: ${{ steps.derive_workspace.outputs.workspace }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.20
        with:
          tag: ${{ inputs.tag }}
      - name: "Derive workspace"
        id: derive_workspace
        uses: NHSDigital/uec-dos-management/.github/actions/derive-workspace@v0.20

  get-commit-hash:
    name: "Get Commit Hash"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.20
        with:
          tag: ${{ inputs.tag }}
      # - name: "Derive commit hash"
      #   # id: commit_hash
        # uses: NHSDigital/uec-dos-management/.github/actions/derive-commit-hash@v0.20
        # with:
        #   sha: "${GITHUB_SHA}"
      - name: "Output commit hash"
        id: commit_hash
        run: |
            commit_hash=$(git rev-parse --short "$GITHUB_SHA")
            echo "commit hash: [$commit_hash]"
            echo "commit_hash=$commit_hash" >> $GITHUB_OUTPUT

  derive-artefact-bucket:
    name: Derive artefact bucket
    runs-on: ubuntu-latest
    outputs:
      artefact_bucket_name: ${{ steps.identify_bucket.outputs.artefact_bucket_name }}
    needs:
      [
        echo-metadata
      ]
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.20
        with:
          tag: ${{ inputs.tag }}
      - name: "Identify domain repository bucket"
        id: identify_bucket
        uses: NHSDigital/uec-dos-management/.github/actions/derive-artefact-bucket@v0.20
        with:
          # environment: ${{ inputs.environment }}
          # workspace: ${{ needs.derive-workspace.outputs.workspace }}
          domain: ${{ needs.echo-metadata.outputs.reponame }}
