name: Metadata workflow

on:
  workflow_call:
    inputs:
        tag:
          description: "The git tag to checkout, this defaults to the head of the triggering branch"
          required: false
          type: string
        workflow_timeout:
          description: "Timeout duration in minutes"
          required: false
          default: 5
          type: number
    outputs:
      reponame:
        description: "The name of the code repo"
        value: "${{ jobs.echo-metadata.outputs.reponame }}"
      workspace:
        description: "The name of the workspace that we interacting with"
        value: "${{ jobs.derive-workspace.outputs.workspace }}"

jobs:
  code-line-count:
    name: "Code Line Count"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.19
        with:
          tag: ${{ inputs.tag }}
      - name: "Code line count"
        uses: NHSDigital/uec-dos-management/.github/actions/code-line-count@v0.19

  echo-metadata:
    name: "Get Metadata"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      reponame: ${{ steps.get_metadata.outputs.reponame }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.19
        with:
          tag: ${{ inputs.tag }}
      - name: "Get metadata"
        id: get_metadata
        uses: NHSDigital/uec-dos-management/.github/actions/metadata@v0.19

  derive-workspace:
    name: "Derive Workspace"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      workspace: ${{ steps.derive_workspace.outputs.workspace }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.19
        with:
          tag: ${{ inputs.tag }}
      - name: "Derive workspace"
        id: derive_workspace
        uses: NHSDigital/uec-dos-management/.github/actions/derive-workspace@v0.19

  generate-commit-hash:
    name: "Generate Commit Hash"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    outputs:
      reponame: ${{ steps.get_metadata.outputs.reponame }}
      commithash: ${{ steps.commit_hash.outputs.commithash }}
    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.19
        with:
          tag: ${{ inputs.tag }}
      - name: "Output commit hash"
        id: commit_hash
        run: | 
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            echo "output [$git_hash]"
            echo "git_hash=$git_hash" >> $GITHUB_OUTPUT

