name: Metadata workflow

on:
  workflow_call:
    inputs:
        git_ref:
          description: "The git tag to checkout or current branch if not passed in"
          required: false
          default: ''
          type: string
    outputs:
      reponame:
        description: "The name of the repo"
        value: "${{ jobs.echo-metadata.outputs.reponame }}"
      tf_max_version:
        description: "The max version of terraform that the code supports"
        value: "${{ jobs.derive-tf-version.outputs.tf_max_version }}"

jobs:
  code-line-count:
    name: "Code Line Count"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Code line count"
        uses: ./.github/actions/code-line-count
        with:
          git_ref: ${{ inputs.git_ref }}
  derive-tf-version:
    name: "Derive TF Version"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      tf_max_version: ${{ steps.derive_tf_version.outputs.tf_max_version }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Derive TF Version"
        id: derive_tf_version
        uses: ./.github/actions/derive-tf-version
        with:
          git_ref: ${{ inputs.git_ref }}
  echo-metadata:
    name: "Get Metadata"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    outputs:
      reponame: ${{ steps.get_metadata.outputs.reponame }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Get metadata2 step"
        id: get_metadata
        uses: ./.github/actions/metadata
        with:
          git_ref: ${{ inputs.git_ref }}

