name: Pipeline Deploy Account Level Infrastructure
# TODO remove task branch,
# revert workspace change
# revert action to apply,
# revert to original stacks array
on:
  push:
    branches:
      - 'main'
      - 'task/DR-971_Use_ssm_parameters'

jobs:
    metadata:
      name: "Get Metadata"
      uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.25

    deploy-account-infrastructure-apply:
        name: "Deploy account level infrastructure"
        needs:
          [
            metadata,
          ]
        uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.25
        with:
          environment: mgmt
          domain: "uec-dos-management"
          workspace: default
          # workspace: ${{ needs.metadata.outputs.workspace }}
          # stacks: "['terraform_management','github-runner','dos-artefacts']"
          stacks: "['dos-artefacts']"
          # action: apply
          action: plan
        secrets: inherit
    slack-notifications:
      needs: [
        metadata,
        deploy-account-infrastructure-apply,
      ]
      if: always()
      uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.25
      with:
        env: mgmt
      secrets: inherit


