name: Pipeline Deployment Application Development Environment

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  metadata:
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  deploy-service:
    name: "Deploy Service"
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/deploy-service.yaml
    with:
      tf_version: ${{ needs.metadata.outputs.tf_max_version }}
      tag: DR-596
      environment: dev
      workspace: DR-596
      stacks: application
      action: plan
    secrets: inherit

  echo-repo-name:
    name: "Echo repo name"
    needs:
      [
        metadata,
      ]
    runs-on: ubuntu-latest
    steps:
      - id: echo
        run: |
          echo "Repo name: ${{ needs.metadata.outputs.reponame }}"
          echo "TF Version: ${{ needs.metadata.outputs.tf_max_version }}"

  quality-checks:
    name: Run quality checks
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/quality_checks.yaml
    with:
      env: mgmt
      repo_name : ${{ needs.metadata.outputs.reponame }}
      stack: '["github-runner", "terraform_management"]'
      tf_version: ${{ needs.metadata.outputs.tf_max_version }}
    secrets: inherit


  # unit-tests:
  #   name: Run unit test
  #   needs:
  #     [
  #       quality-checks,
  #     ]
  #   uses: ./.github/workflows/unit-test.yaml
  #   with:
  #     github_environment: dev
  #   secrets: inherit

  # build:
  #   name: Build artefacts
  #   uses: ./.github/workflows/unit-test.yaml

  # deploy:
  #   name: Deploy application
  #   needs:
  #     [
  #       build,
  #     ]


  # slack-notifications:
  #   needs: [
  #     build-and-deploy-application-code,
  #     unit-tests,
  #     deploy-support-tools-infrastructure,
  #     deploy-vpc-vpn-infrastructure,
  #   ]
  #   if: always()
  #   uses: ./.github/workflows/slack-notifications.yaml
  #   with:
  #     env: dev
  #   secrets: inherit

