name: Pipeline Deployment React Application Development Environment

on:
  push:
    branches:
      - main
      - 'task/*'

env:
  DOMAIN: uec-dos-management
  PROJECT: dos

jobs:
  metadata:
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml
    with:
      project: ${{ env.PROJECT }}
      domain: ${{ env.DOMAIN }}

  deploy-infrastructure-apply:
    name: "Apply Deploy Infrastructure"
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks: "['ui-test-stack']"
      action: apply
      workflow_timeout: 10
    secrets: inherit

  build-react-application:
    name: "Build react application code"
    needs: [
      metadata,
      deploy-infrastructure-apply,
    ]
    uses: ./.github/workflows/build-react-app.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: ${{ needs.metadata.outputs.reponame }}
      commit_hash: ${{ needs.metadata.outputs.commit_hash }}
      artefact_bucket_name: ${{ needs.metadata.outputs.artefact_bucket_name }}
    secrets: inherit

  deploy-react-application:
    name: "Deploy react application code"
    needs: [
      metadata,
      deploy-infrastructure-apply,
      build-react-application
    ]
    uses: ./.github/workflows/deploy-react-app.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: ${{ needs.metadata.outputs.reponame }}
      commit_hash: ${{ needs.metadata.outputs.commit_hash }}
      artefact_bucket_name: ${{ needs.metadata.outputs.artefact_bucket_name }}
    secrets: inherit

  test-react-application:
    name: "Run ui tests against react app"
    needs: [
      metadata,
      deploy-react-application
    ]
    uses: ./.github/workflows/ui-test.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
    secrets: inherit

  slack-notifications:
    needs: [
      metadata,
      deploy-infrastructure-apply,
      deploy-react-application,
      test-react-application
    ]
    if: always()
    uses: ./.github/workflows/slack-notifications.yaml
    with:
      env: mgmt
    secrets: inherit
