name: Pipeline Deployment Application Development Environment

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  metadata:
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  quality-checks:
    name: Run quality checks
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/quality-checks.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      stacks: '["github-runner", "terraform_management"]'
    secrets: inherit

  deploy-infrastructure-plan:
    name: "Plan Deploy Infrastructure"
    needs:
      [
        metadata,
        quality-checks,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks: "['test-stack-1', 'test-stack-2']"
      action: plan
    secrets: inherit

  deploy-infrastructure-apply:
    name: "Apply Deploy Infrastructure"
    needs:
      [
        metadata,
        deploy-infrastructure-plan,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks: "['test-stack-1']"
      action: apply
    secrets: inherit

  unit-tests:
    name: Run unit test
    needs:
      [
        quality-checks,
        metadata,
      ]
    uses: ./.github/workflows/unit-test.yaml
    with:
      env: mgmt
    secrets: inherit

  test-derive-commit-hash:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: test-derive-commit-hash-latest
        uses: NHSDigital/uec-dos-management/.github/actions/derive-commit-hash@v0.41
        with:
          commit-hash: "latest"
      - name: test-derive-commit-hash
        uses: NHSDigital/uec-dos-management/.github/actions/derive-commit-hash@v0.41
        with:
          commit-hash: "abc123def"

  slack-notifications:
    needs: [
      metadata,
      quality-checks,
      deploy-infrastructure-plan,
      deploy-infrastructure-apply,
      unit-tests
    ]
    if: always()
    uses: ./.github/workflows/slack-notifications.yaml
    with:
      env: mgmt
    secrets: inherit
