name: Pipeline Deployment Application Development Environment

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  metadata:
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  quality-checks:
    name: Run quality checks
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/quality-checks.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      stacks: '["github-runner", "terraform_management"]'
    secrets: inherit

  deploy-infrastructure-plan:
    name: "Plan Deploy Infrastructure"
    needs:
      [
        metadata,
        quality-checks,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks: "['test-stack-1', 'test-stack-2']"
      action: plan
    secrets: inherit

  deploy-infrastructure-apply:
    name: "Apply Deploy Infrastructure"
    needs:
      [
        metadata,
        deploy-infrastructure-plan,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks: "['test-stack-1']"
      action: apply
    secrets: inherit


  deploy-infrastructure-destroy:
    name: "Destroy Deploy Infrastructure"
    needs:
      [
        metadata,
        deploy-infrastructure-apply,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks: "['test-stack-1']"
      action: destroy
      workflow_timeout: 10
    secrets: inherit

  unit-tests:
    name: Run unit test
    needs:
      [
        quality-checks,
        metadata,
      ]
    uses: ./.github/workflows/unit-test.yaml
    with:
      env: mgmt
    secrets: inherit

  slack-notifications:
    needs: [
      metadata,
      quality-checks,
      deploy-infrastructure-plan,
      deploy-infrastructure-apply,
      deploy-infrastructure-destroy,
      unit-tests,
    ]
    if: always()
    uses: ./.github/workflows/slack-notifications.yaml
    with:
      env: mgmt
    secrets: inherit

  call-commit-hash:
    name: "call Commit Hash"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}

    needs: generate-commit-hash
    uses: ./.github/workflows/metadata.yaml
    with:
      - run: echo "commit hash [${{needs.generate-commit-hash.outputs.commit_hash}}]"
    secrets: inherit
