name: Pipeline Deploy Account Level Infrastructure

on:
  push:
    branches:
      - 'main'
      - 'task/*'

jobs:
    metadata:
      name: "Get Metadata"
      uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.3
    deploy-account-infrastructure-apply:
        name: "Deploy account level infrastructure"
        needs:
          [
            metadata,
          ]
        uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.3
        with:
          environment: dev
          domain: "uec-dos-management"
          workspace: ${{ needs.metadata.outputs.workspace }}
          stacks: "['github-runner','terraform_management']"
          action: plan
        secrets: inherit
    slack-notifications:
      needs: [
        metadata,
        deploy-account-infrastructure-apply,
      ]
      if: always()
      uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.3
      with:
        env: dev
      secrets: inherit


