name: React metadata workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment to deploy into"
        required: true
        type: string
      workspace:
        description: "The name of the workspace to deploy the application into"
        required: true
        type: string
      repo_name:
        description: "The name of the code repository"
        required: true
        type: string
      tag:
        description: "The git tag to checkout, this defaults to the head of the triggering branch"
        required: false
        type: string
    outputs:
      spa_bucket_name:
        description: "The name of the s3 bucket holding spa code"
        value: "${{ jobs.derive-spa-bucket-name.outputs.spa_bucket_name }}"

jobs:
  derive-spa-bucket-name:
    name: "Derive name of s3 bucket to host SPA"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    outputs:
      spa_bucket_name: ${{ steps.derive_spa_bucket.outputs.spa_bucket_name }}

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@v0.11
        with:
          tag: ${{ inputs.tag }}
      - name: Configure AWS Credentials
        uses: NHSDigital/uec-dos-management/.github/actions/configure-credentials@v0.11
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}

      - name: Derive spa bucket
        id: derive_spa_bucket
        uses: NHSDigital/uec-dos-management/.github/actions/derive-frontend-bucket@task/DR-780_React_flows_and_scripts
        with:
          repo_name: ${{ inputs.repo_name }}
          environment: ${{ inputs.environment }}
          workspace: ${{ inputs.workspace }}
