on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  sparse-checkout-diff-repo:
    name: "Sparse checkout of different repo"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: "Checkout repo"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@task/DR-5967_Sparse_checkout_repo
      - name: "Check sparse checkout"
        shell: bash
        run : |
          echo $(eval dir)
      - name: "Go into sparse checkout area"
        shell: bash
        run : |
          cd uec-dos-management2
          echo $(eval dir)
      - name: "Test that the scripts directory is present"
        shell: bash
        run : |
          cd scripts
          echo $(eval dir)
