name: Test full application build

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  metadata:
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  build-full-application:
    name: Build full application
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/build-full-application.yaml
    with:
      environment: int
      workspace: ${{ needs.metadata.outputs.workspace }}
      triggering_repo: 'uec-dos-service-management'
      triggering_repo_commit_hash: '7be3b06'
      multi_domain: 'true'
    secrets: inherit
