name: Test full application build

# Note to succeed this needs artefacts for your chosen triggering repo to exist in
# the repo's artefact repository (s3) in a directory that relates to your dos-management workspace
#  but references the commit hash used to create that artefact
on:
  workflow_dispatch:
    inputs:
      triggering_repo:
        description: "Specify name of the triggering repo eg uec-dos-service-management"
        required: true
        type: string
      triggering_repo_commit_hash:
        description: "Specify the commit hash that holds the artefact"
        required: true
        type: string

jobs:
  metadata:
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  build-full-application:
    name: Build full application
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/build-full-application.yaml
    with:
      environment: int
      workspace: ${{ needs.metadata.outputs.workspace }}
      triggering_repo: ${{ inputs.triggering_repo }}
      triggering_repo_commit_hash: ${{ inputs.triggering_repo_commit_hash }}
      multi_domain: 'true'
    secrets: inherit
