name: Test Cleardown Workflow
# Intended to run if
# actor is not the queue bot and
# the branch deleted is either
# a task branch or
# a dependabot branch

on:
  delete:
    branches:
      - 'task/*'
      - dependabot/*

jobs:
  metadata:
    if: ( ${{ github.event.ref_type == 'branch' && github.actor != 'github-merge-queue[bot]' }} )
    name: "Get Metadata"
    uses: ./.github/workflows/metadata.yaml

  deploy-infrastructure-apply:
    name: "Apply Deploy Infrastructure"
    needs:
      [
        metadata,
      ]
    uses: ./.github/workflows/deploy-infrastructure.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks: "['test-stack-3']"
      action: apply
    secrets: inherit

  cleardown-infrastructure:
    name: "Cleardown Infrastructure"
    needs:
      [
        metadata,
        deploy-infrastructure-apply,
      ]
    uses: ./.github/workflows/infrastructure-cleardown.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      domain: "uec-dos-management"
      stacks:
        "[
          'test-stack-1',
          'test-stack-2',
          'test-stack-3',
          'ui-test-stack',
          'lambda-stack',
          'test-ready-for-test-stack',
          'github-runner',
          'terraform_management'
        ]"
      workflow_timeout: 10
    secrets: inherit

  cleardown-artefacts:
    name: "Cleardown Artefacts"
    needs:
      [
        metadata,
        cleardown-infrastructure,

      ]
    uses: ./.github/workflows/artefacts-cleardown.yaml
    with:
      environment: mgmt
      workspace: ${{ needs.metadata.outputs.workspace }}
      artefact_bucket_name: ${{needs.metadata.outputs.artefact_bucket_name}}
    secrets: inherit
