name: Code quality checks workflow

on:
  workflow_call:

    inputs:
      env:
        description: The relevant github environment (for secrets and variables)
        required: true
        type: string
      python_version:
        description: 'Version of python'
        type: string
        default: "3.12"
        required: false
      workflow_timeout:
        description: "Timeout duration in minutes"
        required: false
        default: 5
        type: number

jobs:
  unit-test-python:
    name: "Python unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.workflow_timeout }}
    environment: ${{ inputs.env }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout code"
        uses: NHSDigital/uec-dos-management/.github/actions/checkout-repository@latest
      - name: Configure AWS Credentials
        uses: NHSDigital/uec-dos-management/.github/actions/configure-credentials@latest
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
      - name: "Run python unit test"
        uses: NHSDigital/uec-dos-management/.github/actions/unit-test-python@latest
        with:
          aws_region: ${{ vars.AWS_REGION }}
          python_version: ${{ inputs.python_version }}
      - name: "Archive python code coverage results"
        uses: actions/upload-artifact@v4
        with:
          name: "python-code-coverage-report"
          path: coverage.xml
      - name: Perform static analysis
        uses: NHSDigital/uec-dos-management/.github/actions/perform-static-analysis@latest
        with:
          sonar_organisation_key: ${{ vars.SONAR_ORGANISATION_KEY }}
          sonar_project_key: ${{ vars.SONAR_PROJECT_KEY }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
